language: php
php:
  - 5.3
before_script: composer install
script: return 0
after_script: ./vendor/bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml profiles/bear/modules/bear_*
